### ISSUE TITLE
add ignore option to ignore specific directory

### ISSUE THREAD

**Issue by derycktse** [derycktse/treer#1]
also support regex

**Comment by derycktse** [comment]
added

**Comment by Jesonhu** [comment]
如果存在多个需要忽略的文件夹。例如.git、node_modules需要如何过滤呢。我知道可以使用正则, 但是正则如何写呢？

**Comment by NgeKaworu** [comment]
windows福音,但是 正则匹配失败=- =

**Comment by konglingwen94** [comment]
I have the same problem with regular expressions

**Comment by LuoSK** [comment]
treer -e ./directory.md  -i "/^(\.git|node_modules|hooks)$/"
